let xadado = prompt('isimingizni kiriting')
console.log(`name: ${ xadado }`)
let fayzullayev = prompt('familiyangizni kiriting')
console.log(`family: ${ fayzullayev}`)
let fayzullaye = prompt('yoshingizni kiriting')
console.log(`age: ${ fayzullaye}`)
let fayzullay = prompt('e-mail')
console.log(`e-mail: ${ fayzullay}`)
let fayzulla = prompt('turar joyingiz')
console.log(`accommodation: ${ fayzulla}`)
let fayzull = prompt('jonkami yoki jonkamas')
console.log(`jonka or jonkamas: ${ fayzull}`)
alert(`Hurmatli ${fayzull} bizda mazza qilib baham ko'ring `)
alert(`Bizda ${fayzullaye} yoshlarga yaxshi narsalar bor`)
alert(`bu sayt sizga yoqishi aniq hurmatli ${xadado}`)